# -*- coding: utf-8 -*-
"""Módulo 02 - Atividade 04

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_kyYJg7r3a3Y6VMOnkDyfdU0IQ2aenrk
"""

import numpy as np
import cmath as cm

class Complexo():
  def definirComplexo(self):
    self.real = int(input("Digite a parte real do número: "))
    self.imag = int(input("Digite a parte imaginária do número: "))

  def impressaoComplexo(self):
    print(self.real, "+", self.imag, "i", sep="")

  def somaComplexo(self, n1, n2, n3):
    self.real = n1.real + n2.real + n3.real
    self.imag = n1.imag + n2.imag + n3.imag

  def subtracaoComplexo(self, n1, n2, n3):
    self.real = n1.real - n2.real - n3.real
    self.imag = n1.imag - n2.imag - n3.imag

n1 = Complexo()
n2 = Complexo()
n3 = Complexo()
n4 = Complexo()
n5 = Complexo()

print("Digite o primeiro número complexo: ")
n1.definirComplexo()
print("Número digitado (1): \n", end="")
n1.impressaoComplexo()

print("Digite o segundo número complexo: ")
n2.definirComplexo()
print("Número digitado (2): \n", end="")
n2.impressaoComplexo()

print("Digite o terceiro número complexo: ")
n3.definirComplexo()
print("Número digitado (3): \n", end="")
n3.impressaoComplexo()

print("A soma dos números complexos é:\n", end="")
n4.somaComplexo(n1, n2, n3)
n4.impressaoComplexo()

print("A subtração dos números complexos é:\n", end="")
n5.subtracaoComplexo(n1, n2, n3)
n5.impressaoComplexo()