# -*- coding: utf-8 -*-
"""bubble_sort.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Izk_AQfToHdw9fGq5eGnHKk_rVQeVdEg
"""

import numpy as np
import cmath as cm

TAM = int(input("Digite o tamanho do vetor que você deseja inserir: "))
num = list(map(int, input("\nDigite os números: \n").strip().split()))[:TAM]
print("\nO vetor digitado foi:\n", num)
i = 0
temp = 0
cont = 0

#Bubble sort
for passnum in range(len(num)-1, 0, -1):
  for i in range(passnum):
    if (num[i] > num[i + 1]):
      temp = num[i]
      num[i] = num[i + 1]
      num[i+1] = temp

print("\nO vetor ordenado é:\n", num)